language: ruby
rvm:
  - 1.9.3
  - 1.9.2
before_script:
  - mysql -e 'create database chainlink_test;'
  - psql -c 'create database chainlink_test;' -U postgres
env:
  - ADAPTER=sqlite3
  - ADAPTER=mysql2
  - ADAPTER=postgresql
